const licenses = [
  {
    licenseId: 28,
    title: "License Agreement (EULA)",
    content:
      '<h1>Grant of License</h1>\n<p>\n  <strong>Cleannaija Inc.</strong> ("Licensor") grants you ("Licensee") a limited, non-exclusive,\n  non-transferable license to use this waste management application software, developed in collaboration\n  with <strong>Delta State Government</strong> ("State") and\n  <strong>Delta State Waste Management Board</strong> ("Board").\n</p>\n\n<h2>Permitted Uses</h2>\n<p>\n  The Licensee may install and use the Application on authorized devices for personal waste\n  management activities, access features related to waste collection and recycling services, and utilize\n  reporting tools in compliance with State and Board requirements.\n</p>\n\n<h2>Restrictions</h2>\n<p>\n  The Licensee may not reverse engineer, modify, or distribute the Application software, use the\n  Application for commercial purposes without written consent from the Licensor, State, and Board, or\n  attempt to bypass security measures implemented by the Licensor.\n</p>\n\n<h2>Intellectual Property Rights</h2>\n<p>\n  The Licensor retains all rights to the Application software. The State and Board maintain rights to\n  regulatory frameworks, guidelines, and public domain waste management information integrated into\n  the Application.\n</p>\n\n<h2>Updates and Modifications</h2>\n<p>\n  The Licensor may provide updates to maintain compatibility with State regulations and Board\n  requirements. Continued use after updates constitutes acceptance of modified terms.\n</p>\n\n<h2>Compliance Requirements</h2>\n<p>\n  The Licensee agrees to use the Application in accordance with State environmental laws and Board\n  regulations governing waste management practices.\n</p>\n\n<h2>Termination of License</h2>\n<p>\n  This license terminates automatically if the Licensee violates terms, upon discontinuation of services\n  by the Licensor, or upon changes in State or Board authorization for the Application.\n</p>\n',
    validTill: "2099-12-31T00:00:00",
    licenseType: "END_USER_LICENSE_AGREEMENT",
    scope: "CLIENTS",
    stateId: 10,
  },
  {
    licenseId: 27,
    title: "Payment Terms And Conditions",
    content:
      '<h1>Service Fees</h1>\n<p>\n  <strong>Cleannaija Inc.</strong> ("Company") establishes service fees for waste management services\n  provided through this Application, subject to rate structures approved by\n  <strong>Delta State Government</strong> ("State") and\n  <strong>Delta State Waste Management Board</strong> ("Board").\n</p>\n\n<h2>Payment Methods</h2>\n<p>\n  Users may pay through approved electronic payment methods integrated into the Application. All\n  payment processing complies with State consumer protection laws and Board financial oversight\n  requirements.\n</p>\n\n<h2>Billing Cycles</h2>\n<p>\n  The Company will bill Users according to service usage and subscription levels, with billing practices\n  subject to State utility regulations and Board approval where applicable.\n</p>\n\n<h2>Late Payment and Penalties</h2>\n<p>\n  Late payment fees and service suspension policies are established by the Company in accordance\n  with State consumer protection laws and may not exceed limits set by the Board.\n</p>\n\n<h2>Refund Policy</h2>\n<p>\n  Refunds for services are processed according to Company policy, State consumer rights laws, and\n  Board dispute resolution procedures. Users may appeal refund decisions through State regulatory\n  channels.\n</p>\n\n<h2>Tax Obligations</h2>\n<p>\n  Users are responsible for applicable taxes on services. The Company will collect State-mandated taxes\n  and fees as required by the Board and remit them to appropriate State agencies.\n</p>\n\n<h2>Price Changes</h2>\n<p>\n  Service rate changes require advance notice to Users and, where applicable, approval from State\n  regulatory authorities and the Board before implementation.\n</p>\n\n<h2>Disputed Charges</h2>\n<p>\n  Users may dispute charges through the Company\'s resolution process, State consumer protection\n  agencies, or Board complaint procedures, maintaining rights under State law.\n</p>\n',
    validTill: "2099-12-31T00:00:00",
    licenseType: "PAYMENT_TERMS_AND_CONDITIONS",
    scope: "CLIENTS",
    stateId: 10,
  },
  {
    licenseId: 26,
    title: "Terms And Conditions",
    content:
      '<h2>Acceptance of Terms</h2>\n  <p>\n    By accessing and using this waste management application ("Application"), you ("User") agree to be\n    bound by these Terms and Conditions. This agreement is between you, <strong>Cleannaija Inc.</strong>\n    ("Company"), and is operated in collaboration with the <strong>Delta State Government</strong> ("State")\n    through the <strong>Delta State Waste Management Board</strong> ("Board").\n  </p>\n\n  <h2>Service Description</h2>\n  <p>\n    The Company provides waste management services through this Application in partnership with the\n    State and under the oversight of the Board. Services include waste collection scheduling, disposal\n    tracking, recycling information, and related waste management functionalities.\n  </p>\n\n  <h2>User Responsibilities</h2>\n  <p>\n    Users must provide accurate information, comply with local waste management regulations as\n    established by the State and Board, use the Application lawfully, and respect intellectual property\n    rights of the Company, State, and Board.\n  </p>\n\n  <h2>Company Obligations</h2>\n  <p>\n    The Company agrees to maintain the Application, provide reliable waste management services, protect\n    user data in accordance with applicable laws, and operate in compliance with State regulations and\n    Board guidelines.\n  </p>\n\n  <h2>State and Board Authority</h2>\n  <p>\n    The State, through the Board, maintains regulatory oversight of waste management operations,\n    establishes environmental compliance standards, and may modify regulations that affect service\n    delivery.\n  </p>\n\n  <h2>Limitation of Liability</h2>\n  <p>\n    Neither the Company, State, nor Board shall be liable for indirect, incidental, or consequential damages\n    arising from use of the Application or services, except as required by applicable law.\n  </p>\n\n  <h2>Termination</h2>\n  <p>\n    Either party may terminate access to the Application with reasonable notice. The Company reserves\n    the right to suspend services for violation of terms, subject to State and Board regulations.\n  </p>\n',
    validTill: "2099-12-31T00:00:00",
    licenseType: "TERMS_AND_CONDITIONS",
    scope: "CLIENTS",
    stateId: 10,
  },

  {
    licenseId: 25,
    title: "Privacy Policy",
    content:
      '<h1>Information Collection</h1>\n<p>\n  <strong>CleanNaija Inc.</strong> ("Company") collects personal and usage information necessary to\n  provide waste management services, in compliance with <strong>Delta State Government</strong> ("State")\n  privacy laws and <strong>Delta State Waste Management Board</strong> ("Board") data requirements.\n</p>\n\n<h2>Types of Data Collected</h2>\n<p>\n  We collect contact information, service addresses, waste generation data, payment information, and\n  usage analytics. Environmental data may be shared with the State and Board for regulatory compliance\n  and planning purposes.\n</p>\n\n<h2>Use of Information</h2>\n<p>\n  Information is used to provide services, process payments, ensure regulatory compliance with State\n  and Board requirements, improve service delivery, and communicate with Users about account and\n  service matters.\n</p>\n\n<h2>Data Sharing</h2>\n<p>\n  Personal information may be shared with the State and Board for regulatory reporting, environmental\n  monitoring, and public health purposes. We do not sell personal information to third parties.\n</p>\n\n<h2>Data Security</h2>\n<p>\n  The Company implements security measures to protect User information, maintains systems\n  compliant with State data protection standards, and follows Board guidelines for environmental data\n  handling.\n</p>\n\n<h2>User Rights</h2>\n<p>\n  Users may access, correct, or request deletion of personal information subject to regulatory retention\n  requirements by the State and Board. Users may opt out of non-essential communications while\n  maintaining service-related notifications.\n</p>\n\n<h2>Retention Period</h2>\n<p>\n  Data is retained as long as necessary for service provision and to meet State recordkeeping\n  requirements and Board regulatory obligations, typically ranging from 3–7 years after account closure.\n</p>\n\n<h2>Contact for Privacy Concerns</h2>\n<p>\n  Users may contact the Company\'s privacy officer, file complaints with State consumer protection\n  agencies, or address concerns to the Board regarding data handling practices.\n</p>\n',
    validTill: "2099-12-31T00:00:00",
    licenseType: "PRIVACY_POLICY",
    scope: "CLIENTS",
    stateId: 10,
  },
  {
    licenseId: 30,
    title: "Subscription Renewal",
    content:
      '<h1>Automatic Renewal</h1>\n<p>\n  Waste management services provided by <strong>Cleannaija Inc.</strong> ("Company") automatically\n  renew according to subscription terms, subject to continued authorization by\n  <strong>Delta State Government</strong> ("State") and\n  <strong>Delta State Waste Management Board</strong> ("Board").\n</p>\n\n<h2>Renewal Terms</h2>\n<p>\n  Subscriptions renew for equivalent periods unless modified by User, Company, or due to changes in\n  State regulations or Board service requirements. Rate changes require advance notice per State\n  consumer protection laws.\n</p>\n\n<h2>Cancellation Rights</h2>\n<p>\n  Users may cancel subscriptions with appropriate notice, subject to State consumer rights and Board\n  service continuity requirements. Certain essential waste services may require alternative arrangements\n  approved by the Board.\n</p>\n\n<h2>Service Level Changes</h2>\n<p>\n  Users may modify service levels during renewal periods, upgrade or downgrade services based on\n  availability and State regulatory requirements, and request special accommodations through Board-\n  approved procedures.\n</p>\n\n<h2>Renewal Notifications</h2>\n<p>\n  The Company will provide renewal notices as required by State law, include information about rate\n  changes and service modifications, and notify Users of any changes in State or Board requirements\n  affecting services.\n</p>\n\n<h2>Non-Renewal Consequences</h2>\n<p>\n  Failure to renew may result in service suspension, removal of Company equipment, and notification to\n  State authorities and the Board as required for public health and environmental protection.\n</p>\n\n<h2>Dispute Resolution</h2>\n<p>\n  Renewal disputes may be resolved through Company customer service, State consumer protection\n  agencies, Board complaint procedures, or alternative dispute resolution methods approved by State\n  regulations.\n</p>\n\n<h2>Regulatory Changes</h2>\n<p>\n  Subscription terms may be modified to comply with new <strong>Nigeria</strong> federal laws, State laws\n  or Board regulations, with Users receiving notice of changes and options for service adjustment or\n  cancellation as permitted by <strong>Nigeria</strong> federal and State law.\n</p>\n',
    validTill: "2099-12-31T00:00:00",
    licenseType: "SUBSCRIPTION_RENEWAL",
    scope: "CLIENTS",
    stateId: 10,
  },
  {
    licenseId: 29,
    title: "Waste Storage And Tools Replacement",
    content:
      '<h1>Equipment Provision</h1>\n<p>\n  <strong>Cleannaija Inc.</strong> ("Company") provides waste storage containers and collection tools as\n  part of service delivery, in accordance with standards set by <strong>Delta State Government</strong> ("State")\n  and <strong>Delta State Waste Management Board</strong> ("Board").\n</p>\n\n<h2>Container Specifications</h2>\n<p>\n  All containers meet State environmental standards and Board safety requirements, are appropriate for\n  designated waste types, include proper labeling as required by State regulations, and comply with\n  local ordinances.\n</p>\n\n<h2>Replacement Policy</h2>\n<p>\n  The Company will replace damaged or worn containers at no charge when damage results from normal\n  use, within reasonable timeframes established in consultation with the Board, and according to\n  replacement schedules that meet State service standards.\n</p>\n\n<h2>User Responsibilities</h2>\n<p>\n  Users must properly maintain containers, use equipment only for designated waste types as specified\n  by State and Board guidelines, report damage or loss promptly to the Company, and allow reasonable\n  access for container inspection.\n</p>\n\n<h2>Lost or Damaged Equipment</h2>\n<p>\n  Replacement costs may apply for equipment lost or damaged due to User negligence, misuse contrary\n  to State guidelines, or failure to follow Board-approved waste handling procedures.\n</p>\n\n<h2>Specialized Equipment</h2>\n<p>\n  Requests for specialized containers for hazardous or medical waste must comply with State\n  regulations and Board certification requirements, with additional fees and handling procedures as\n  applicable.\n</p>\n\n<h2>Return of Equipment</h2>\n<p>\n  Upon service termination, Users must return Company equipment in reasonable condition, with costs\n  for unreturned equipment subject to State consumer protection limits and Board oversight.\n</p>\n',
    validTill: "2099-12-31T00:00:00",
    licenseType: "WASTE_STORAGE_AND_TOOLS_REPLACEMENT",
    scope: "CLIENTS",
    stateId: 10,
  },
];
