import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Providers from "@/context/providers";

const productSans = localFont({
  src: "../public/icons/Product-Sans-Regular.ttf",
});

const slackey = localFont({
  src: "../public/icons/Slackey-Regular.ttf",
});

export const metadata: Metadata = {
  title: "Pluto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${productSans.className} antialiased`}>
        <Providers>{children}</Providers>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
